apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  type: ClusterIP
  clusterIP: 10.100.99.99
  selector:
    app: app
  ports:
      - port: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          # livenessProbe:
          #   exec:
          #     command:
          #     - sh
          #     - /dog.sh
          #   initialDelaySeconds: 20
          #   periodSeconds: 5
          image: 717189823417.dkr.ecr.eu-central-1.amazonaws.com/app:latest
          ports:
            - containerPort: 3000