apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  type: ClusterIP
  clusterIP: 10.100.99.91
  selector:
    app: api
  ports:
      - port: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      serviceAccountName: 
      containers:
        - name: api
          # livenessProbe:
          #   exec:
          #     command:
          #     - sh
          #     - /dog.sh
          #   initialDelaySeconds: 20
          #   periodSeconds: 5
          image: api
          imagePullPolicy: Never
          ports:
            - containerPort: 3000