kind: Service
apiVersion: v1
metadata:
  name: caddy
  
  annotations:
    metallb.universe.tf/address-pool: first-pool
  labels:
    app: caddy
spec:
  type: LoadBalancer
  selector:
    app: caddy
  ports:
    - name: http
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy
  
  labels:
    app: caddy
spec:
  selector:
    matchLabels:
      app: caddy
  template:
    metadata:
      labels:
        app: caddy
    spec:
      serviceAccountName: 
      containers:
      - name: caddy
        # livenessProbe:
        #   exec:
        #     command:
        #     - sh
        #     - /dog.sh
        #   initialDelaySeconds: 20
        #   periodSeconds: 5
        image: caddy
        imagePullPolicy: Never
        ports:
          - containerPort: 3000
            name: http
        securityContext:
          privileged: true