apiVersion: v1
kind: Service
metadata:
  name: pma
  
spec:
  type: ClusterIP
  clusterIP: 10.100.99.80
  selector:
    app: pma
  ports:
      - port: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pma
  
  labels:
    app: pma
spec:
  selector:
    matchLabels:
      app: pma
  template:
    metadata:
      labels:
        app: pma
    spec:
      serviceAccountName: 
      containers:
        - name: pma
          # livenessProbe:
          #   exec:
          #     command:
          #     - sh
          #     - /dog.sh
          #   initialDelaySeconds: 20
          #   periodSeconds: 5
          image: pma
          imagePullPolicy: Never
          ports:
            - containerPort: 3000